<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>

    <PackageId>AminTools</PackageId>
    <Version>1.0.1</Version>
    <Authors>MintyBueno</Authors>
    <Description>Useful tools and helpers.</Description>

    <RepositoryUrl>https://github.com/MintyBueno/AminTools</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  
</PropertyGroup>

</Project>
